# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/lucyhuhn/jenkins_compose/jenkins_configuration:/var/jenkins_home
    networks:
      - minikube
networks:
  minikube:
    driver: bridge
